### ISSUE TITLE
PHP Port

### ISSUE THREAD

**Issue by tajmone** [tajmone/fuzzy-search#3]
There's an [PHP port] of __fts_fuzzy_match__ v0.1.0, by @detectiveYarmas.

- [x]   [Ask the author for permission] to include his port into the project under FOSS license.
- [x]   Add the port to the project.

[PHP port]: https://github.com/detectiveYarmas/lib_fts/blob/master/code/fts_fuzzy_match.php

[Ask the author for permission]: https://github.com/detectiveYarmas/detectiveYarmas.github.io/issues/1

**Comment by detectiveYarmas** [comment]
Feel free to use it, I honestly forgot I ever wrote any of this. Good luck with your project!

**Comment by tajmone** [comment]
Thanks a lot @detectiveYarmas !

I've included it in this folder, under the same CC0/public domain license of the project:

https://github.com/tajmone/fuzzy-search/tree/master/fts_fuzzy_match/0.1.0/php/
