### ISSUE TITLE
Update JavaScript Version of FTS Fuzzy Match to v0.2.0

### ISSUE THREAD

**Issue by tajmone** [tajmone/fuzzy-search#7]
The project needs help from someone fluent in JavaScript to update [Forrest Smith]'s [JavaScript version] of __fts_fuzzy_match__ v0.1.0 to [v0.2.0 of the algorithm].

The updated file should be created in:

    /fts_fuzzy_match/0.2.0/js/

The JavaScript version is released into the public domain, but the coder is free to use any license he/she pleases, as long as he/she credits the original author.

[JavaScript version]: https://github.com/tajmone/fuzzy-search/tree/master/fts_fuzzy_match/0.1.0/js/
[Forrest Smith]: https://github.com/forrestthewoods "View Forrest Smith's GitHub profile"
[v0.2.0 of the algorithm]: https://github.com/tajmone/fuzzy-search/tree/master/fts_fuzzy_match/0.2.0/cpp/ "View C++ source of algorithm v0.2.0"

**Comment by nrgwsth** [comment]
@tajmone I'd like to help.

**Comment by tajmone** [comment]
Hi @nrgwsth,

that's great! Feel free to make a PR for the version 0.2.0 of the algorithm. I'm not really of the JS league, so I'm not fluent in that language.

Forrest Smith only update the C++ version of his algorithm to v0.2.0, but by diffing the two C++ versions you can see that he basically just added an extra recursion to attempt match variations in case the same pattern could lead to a higher score.
